/*
 * This file is generated by jOOQ.
 */
package com.daimler.exercise.db.autogenerated.tables;


import com.daimler.exercise.db.autogenerated.Public;
import com.daimler.exercise.db.autogenerated.tables.records.BusStopRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStop extends TableImpl<BusStopRecord> {

    private static final long serialVersionUID = -1142384172;

    /**
     * The reference instance of <code>public.bus_stop</code>
     */
    public static final BusStop BUS_STOP = new BusStop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BusStopRecord> getRecordType() {
        return BusStopRecord.class;
    }

    /**
     * The column <code>public.bus_stop.timestamp</code>.
     */
    public final TableField<BusStopRecord, Long> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.bus_stop.line_id</code>.
     */
    public final TableField<BusStopRecord, String> LINE_ID = createField("line_id", org.jooq.impl.SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>public.bus_stop.direction</code>.
     */
    public final TableField<BusStopRecord, String> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>public.bus_stop.journey_pattern_id</code>.
     */
    public final TableField<BusStopRecord, String> JOURNEY_PATTERN_ID = createField("journey_pattern_id", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>public.bus_stop.time_frame</code>.
     */
    public final TableField<BusStopRecord, Timestamp> TIME_FRAME = createField("time_frame", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.bus_stop.vehicle_journey_id</code>.
     */
    public final TableField<BusStopRecord, Long> VEHICLE_JOURNEY_ID = createField("vehicle_journey_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.bus_stop.operator</code>.
     */
    public final TableField<BusStopRecord, String> OPERATOR = createField("operator", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>public.bus_stop.congestion</code>.
     */
    public final TableField<BusStopRecord, Boolean> CONGESTION = createField("congestion", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.bus_stop.latitude</code>.
     */
    public final TableField<BusStopRecord, BigDecimal> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.bus_stop.longitude</code>.
     */
    public final TableField<BusStopRecord, BigDecimal> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.bus_stop.delay</code>.
     */
    public final TableField<BusStopRecord, Integer> DELAY = createField("delay", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.bus_stop.block_id</code>.
     */
    public final TableField<BusStopRecord, Integer> BLOCK_ID = createField("block_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.bus_stop.vehicle_id</code>.
     */
    public final TableField<BusStopRecord, Integer> VEHICLE_ID = createField("vehicle_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.bus_stop.stop_id</code>.
     */
    public final TableField<BusStopRecord, String> STOP_ID = createField("stop_id", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>public.bus_stop.at_bus_stop</code>.
     */
    public final TableField<BusStopRecord, Boolean> AT_BUS_STOP = createField("at_bus_stop", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.bus_stop</code> table reference
     */
    public BusStop() {
        this(DSL.name("bus_stop"), null);
    }

    /**
     * Create an aliased <code>public.bus_stop</code> table reference
     */
    public BusStop(String alias) {
        this(DSL.name(alias), BUS_STOP);
    }

    /**
     * Create an aliased <code>public.bus_stop</code> table reference
     */
    public BusStop(Name alias) {
        this(alias, BUS_STOP);
    }

    private BusStop(Name alias, Table<BusStopRecord> aliased) {
        this(alias, aliased, null);
    }

    private BusStop(Name alias, Table<BusStopRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> BusStop(Table<O> child, ForeignKey<O, BusStopRecord> key) {
        super(child, key, BUS_STOP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStop as(String alias) {
        return new BusStop(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BusStop as(Name alias) {
        return new BusStop(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BusStop rename(String name) {
        return new BusStop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BusStop rename(Name name) {
        return new BusStop(name, null);
    }
}
