/*
 * This file is generated by jOOQ.
 */
package com.daimler.exercise.db.autogenerated.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStop implements Serializable {

    private static final long serialVersionUID = 1953628923;

    private Long       timestamp;
    private String     lineId;
    private String     direction;
    private String     journeyPatternId;
    private Timestamp  timeFrame;
    private Long       vehicleJourneyId;
    private String     operator;
    private Boolean    congestion;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private Integer    delay;
    private Integer    blockId;
    private Integer    vehicleId;
    private String     stopId;
    private Boolean    atBusStop;

    public BusStop() {}

    public BusStop(BusStop value) {
        this.timestamp = value.timestamp;
        this.lineId = value.lineId;
        this.direction = value.direction;
        this.journeyPatternId = value.journeyPatternId;
        this.timeFrame = value.timeFrame;
        this.vehicleJourneyId = value.vehicleJourneyId;
        this.operator = value.operator;
        this.congestion = value.congestion;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.delay = value.delay;
        this.blockId = value.blockId;
        this.vehicleId = value.vehicleId;
        this.stopId = value.stopId;
        this.atBusStop = value.atBusStop;
    }

    public BusStop(
        Long       timestamp,
        String     lineId,
        String     direction,
        String     journeyPatternId,
        Timestamp  timeFrame,
        Long       vehicleJourneyId,
        String     operator,
        Boolean    congestion,
        BigDecimal latitude,
        BigDecimal longitude,
        Integer    delay,
        Integer    blockId,
        Integer    vehicleId,
        String     stopId,
        Boolean    atBusStop
    ) {
        this.timestamp = timestamp;
        this.lineId = lineId;
        this.direction = direction;
        this.journeyPatternId = journeyPatternId;
        this.timeFrame = timeFrame;
        this.vehicleJourneyId = vehicleJourneyId;
        this.operator = operator;
        this.congestion = congestion;
        this.latitude = latitude;
        this.longitude = longitude;
        this.delay = delay;
        this.blockId = blockId;
        this.vehicleId = vehicleId;
        this.stopId = stopId;
        this.atBusStop = atBusStop;
    }

    public Long getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getLineId() {
        return this.lineId;
    }

    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    public String getDirection() {
        return this.direction;
    }

    public void setDirection(String direction) {
        this.direction = direction;
    }

    public String getJourneyPatternId() {
        return this.journeyPatternId;
    }

    public void setJourneyPatternId(String journeyPatternId) {
        this.journeyPatternId = journeyPatternId;
    }

    public Timestamp getTimeFrame() {
        return this.timeFrame;
    }

    public void setTimeFrame(Timestamp timeFrame) {
        this.timeFrame = timeFrame;
    }

    public Long getVehicleJourneyId() {
        return this.vehicleJourneyId;
    }

    public void setVehicleJourneyId(Long vehicleJourneyId) {
        this.vehicleJourneyId = vehicleJourneyId;
    }

    public String getOperator() {
        return this.operator;
    }

    public void setOperator(String operator) {
        this.operator = operator;
    }

    public Boolean getCongestion() {
        return this.congestion;
    }

    public void setCongestion(Boolean congestion) {
        this.congestion = congestion;
    }

    public BigDecimal getLatitude() {
        return this.latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public BigDecimal getLongitude() {
        return this.longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public Integer getDelay() {
        return this.delay;
    }

    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    public Integer getBlockId() {
        return this.blockId;
    }

    public void setBlockId(Integer blockId) {
        this.blockId = blockId;
    }

    public Integer getVehicleId() {
        return this.vehicleId;
    }

    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    public String getStopId() {
        return this.stopId;
    }

    public void setStopId(String stopId) {
        this.stopId = stopId;
    }

    public Boolean getAtBusStop() {
        return this.atBusStop;
    }

    public void setAtBusStop(Boolean atBusStop) {
        this.atBusStop = atBusStop;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BusStop (");

        sb.append(timestamp);
        sb.append(", ").append(lineId);
        sb.append(", ").append(direction);
        sb.append(", ").append(journeyPatternId);
        sb.append(", ").append(timeFrame);
        sb.append(", ").append(vehicleJourneyId);
        sb.append(", ").append(operator);
        sb.append(", ").append(congestion);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(delay);
        sb.append(", ").append(blockId);
        sb.append(", ").append(vehicleId);
        sb.append(", ").append(stopId);
        sb.append(", ").append(atBusStop);

        sb.append(")");
        return sb.toString();
    }
}
